In [ ]:
Chocolate Sales: Data Wrangling

In [5]:
import pandas as pd
import warnings

# Read Excel
df = pd.read_excel("C:/Users/Monster/Desktop/Chocolate-Sales.xlsx")

df.head(5)

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04-Jan-22,"$5,320",180
1,Van Tuxwell,India,85% Dark Bars,01-Aug-22,"$7,896",94
2,Gigi Bohling,India,Peanut Butter Cubes,07-Jul-22,"$4,501",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27-Apr-22,"$12,726",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24-Feb-22,"$13,685",184

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   1094 non-null   object
 1   Country        1094 non-null   object
 2   Product        1094 non-null   object
 3   Date           1094 non-null   object
 4   Amount         1094 non-null   object
 5   Boxes Shipped  1094 non-null   int64
dtypes: int64(1), object(5)
memory usage: 51.4+ KB

In [9]:
df.shape

(1094, 6)

In [11]:
df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   1094 non-null   object
 1   Country        1094 non-null   object
 2   Product        1094 non-null   object
 3   Date           1094 non-null   object
 4   Amount         1094 non-null   object
 5   Boxes Shipped  1094 non-null   int64
dtypes: int64(1), object(5)
memory usage: 51.4+ KB

In [15]:
# Remove "$" and cast "Amount" as float
df["Amount"] = (df["Amount"]
    .str.replace("$", "")

)

df["Amount"].head(5)

0     5,320
1     7,896
2     4,501
3    12,726
4    13,685
Name: Amount, dtype: object

In [23]:
df["Amount"] = (df["Amount"].str.replace(",", ""))

In [25]:
df["Amount"].head(1)

0    5320
Name: Amount, dtype: object

In [27]:
df.head(1
       )

     Sales Person Country          Product       Date Amount  Boxes Shipped
0  Jehu Rudeforth      UK  Mint Chip Choco  04-Jan-22  5320             180

In [29]:
df["Amount"] = df["Amount"].astype(float)

In [31]:
df.dtypes

Sales Person      object
Country           object
Product           object
Date              object
Amount           float64
Boxes Shipped      int64
dtype: object

In [33]:
df['Date'] = pd.to_datetime(df['Date'])   
df.dtypes

C:\Users\Monster\AppData\Local\Temp\ipykernel_20460\532320438.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date'] = pd.to_datetime(df['Date'])

Sales Person             object
Country                  object
Product                  object
Date             datetime64[ns]
Amount                  float64
Boxes Shipped             int64
dtype: object

In [35]:
df["Product"].value_counts()
df["Country"].value_counts()

Country
Australia      205
India          184
USA            179
UK             178
Canada         175
New Zealand    173
Name: count, dtype: int64

In [37]:
df["Product"].value_counts()

Product
50% Dark Bites          60
Eclairs                 60
Smooth Sliky Salty      59
White Choc              58
Drinking Coco           56
Spicy Special Slims     54
Organic Choco Syrup     52
After Nines             50
85% Dark Bars           50
Fruit & Nut Bars        50
Milk Bars               49
Peanut Butter Cubes     49
99% Dark & Pure         49
Almond Choco            48
Raspberry Choco         48
Orange Choco            47
Mint Chip Choco         45
Manuka Honey Choco      45
Caramel Stuffed Bars    43
70% Dark Bites          42
Baker's Choco Chips     41
Choco Coated Almonds    39
Name: count, dtype: int64

In [39]:
df["Sales Person"].value_counts()

Sales Person
Kelci Walkden          54
Brien Boise            53
Van Tuxwell            51
Beverie Moffet         50
Dennison Crosswaite    49
Oby Sorrel             49
Ches Bonnell           48
Karlen McCaffrey       47
Gigi Bohling           47
Curtice Advani         46
Kaine Padly            45
Madelene Upcott        45
Marney O'Breen         45
Barr Faughny           43
Jehu Rudeforth         43
Roddy Speechley        43
Gunar Cockshoot        43
Mallorie Waber         41
Jan Morforth           39
Andria Kimpton         39
Husein Augar           38
Dotty Strutley         36
Wilone O'Kielt         34
Rafaelita Blaksland    34
Camilla Castle         32
Name: count, dtype: int64

In [41]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['MonthName'] = df['Date'].dt.strftime('%B')

In [43]:
df.to_excel("Chocolate_Sales_Clean.xlsx", index=False)

In [47]:
df = df.dropna(subset=['Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   1094 non-null   object
 1   Country        1094 non-null   object
 2   Product        1094 non-null   object
 3   Date           1094 non-null   datetime64[ns]
 4   Amount         1094 non-null   float64
 5   Boxes Shipped  1094 non-null   int64
 6   Year           1094 non-null   int32
 7   Month          1094 non-null   int32
 8   MonthName      1094 non-null   object
dtypes: datetime64[ns](1), float64(1), int32(2), int64(1), object(4)
memory usage: 68.5+ KB